# Generated by Django 5.0 on 2024-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='trainer/')),
                ('description', models.TextField()),
            ],
        ),
    ]
