# Generated by Django 5.0 on 2024-02-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': ('Тренер',), 'verbose_name_plural': 'Тренеры'},
        ),
    ]
