# Generated by Django 5.0 on 2024-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('desc', models.TextField(verbose_name='описание')),
                ('salary', models.CharField(max_length=255, verbose_name='зарплата')),
            ],
            options={
                'verbose_name': ('Ваканция',),
                'verbose_name_plural': 'Ваканции',
            },
        ),
    ]
