# Generated by Django 5.0.3 on 2024-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('discription', models.TextField(verbose_name='Отыз')),
                ('discription_ru', models.TextField(null=True, verbose_name='Отыз')),
                ('discription_ky', models.TextField(null=True, verbose_name='Отыз')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('created_ru', models.DateField(auto_now=True, null=True, verbose_name='Дата публикации')),
                ('created_ky', models.DateField(auto_now=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
