# Generated by Django 5.0.3 on 2024-03-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_ky',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_ru',
        ),
    ]
