# Generated by Django 5.0.3 on 2024-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_remove_review_created_ky_remove_review_created_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dol',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
