# Generated by Django 5.0.3 on 2024-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_review_dol_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dol_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='review',
            name='dol_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_ky',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='review',
            name='photo_ru',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Фотография'),
        ),
    ]
