# Generated by Django 5.0.3 on 2024-03-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0005_rename_dol_review_jobtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo_ky',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo_ru',
        ),
    ]
