# Generated by Django 5.0 on 2024-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('p_number', models.CharField(max_length=16, verbose_name='Второй номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Введите почту')),
                ('work_time', models.CharField(max_length=100, verbose_name='Время работы по будням')),
                ('w_time', models.CharField(max_length=100, verbose_name='Время работы по выходным')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('links', models.URLField(blank=True, null=True, verbose_name='Введите ссылку')),
            ],
        ),
    ]
