# Generated by Django 5.0 on 2024-02-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': ('О нас',), 'verbose_name_plural': 'О нас'},
        ),
    ]
