# Generated by Django 5.0 on 2024-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('gruppa', models.CharField(max_length=250, verbose_name='Группа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='abonements/', verbose_name='Фото')),
                ('weekdays', models.CharField(max_length=150, verbose_name='Время секции')),
                ('price_month', models.CharField(max_length=20, verbose_name='Стоимость в месяц')),
                ('price_year', models.CharField(max_length=20, verbose_name='Стоимость в год')),
            ],
        ),
    ]
