# Generated by Django 5.0 on 2024-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=255, verbose_name='номер')),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявление',
            },
        ),
    ]
